'use client';
import { FormEvent, useMemo, useState } from 'react';
import { calculatePayroll, formatEasyWon, formatWon, type CalculationInput } from './payroll';
import { SiteFooter, SiteHeader } from './site-chrome';
import { Guide, GuideLabel } from './input-guide';
const presets = [['간호조무사',2300000],['피부관리사',2500000],['상담실장',3500000],['페이닥터',13000000]] as const;
const initial:CalculationInput={inputType:'net',amount:3500000,dependents:1,children:0,employerSize:'under150',durunuri:false,smallWorkplace:false,overtime:0,night:0,holiday:0,meal:0,childcare:0,transport:0};
function MoneyInput({value,onChange,label}:{value:number;onChange:(v:number)=>void;label:string}){return <input aria-label={label} inputMode="numeric" value={value?value.toLocaleString('ko-KR'):''} onChange={e=>onChange(Number(e.target.value.replace(/\D/g,'')))} placeholder="0"/>}
export default function Home(){
 const[form,setForm]=useState(initial),[submitted,setSubmitted]=useState(initial);const result=useMemo(()=>calculatePayroll(submitted),[submitted]);
 const update=<K extends keyof CalculationInput>(key:K,value:CalculationInput[K])=>setForm(s=>({...s,[key]:value}));
 const submit=(e:FormEvent)=>{e.preventDefault();setSubmitted(form);setTimeout(()=>document.getElementById('result')?.scrollIntoView({behavior:'smooth',block:'start'}),20)};
 return <main><SiteHeader/>
 <section className="hero" id="top"><div className="eyebrow">THE FOUNT · CLINIC OPERATIONS</div><h1>직원 월급, 숫자 하나보다<br/><em>진짜 병원 부담</em>을 보세요.</h1><p>실수령액을 입력하면 세전 급여, 4대보험 사업주분, 퇴직금과 가산수당을 한 번에 계산합니다.</p><div className="hero-metrics"><div><strong>4대보험</strong><span>근로자·사업주 구분</span></div><div><strong>퇴직금</strong><span>매월 1/12 적립</span></div><div><strong>간이세액</strong><span>부양가족 반영</span></div></div></section>
 <section className="calculator-shell" id="calculator"><form className="form-card" onSubmit={submit}><div className="section-head"><div><span className="step">01</span><h2>급여 조건 입력</h2></div><p>월 단위 · 대한민국 원화</p></div>
 <div className="segmented"><button type="button" className={form.inputType==='net'?'active':''} onClick={()=>update('inputType','net')}>실수령액 기준</button><button type="button" className={form.inputType==='gross'?'active':''} onClick={()=>update('inputType','gross')}>총 지급액 기준</button></div>
 <div className="preset-row">{presets.map(([label,amount])=><button type="button" key={label} onClick={()=>update('amount',amount)}><span>{label}</span>{(amount/10000).toLocaleString()}만</button>)}</div>
 <label className="major-field"><GuideLabel title="월 급여액" meaning={form.inputType==='net'?'직원이 통장으로 실제 받고 싶은 금액입니다. 공제액을 역산해 세전 급여를 구합니다.':'근로계약서에 적힌 공제 전 월 급여입니다. 기본급과 고정수당을 합쳐 입력하세요.'} example={form.inputType==='net'?'실수령 350만원 → 3,500,000':'세전 300만원 → 3,000,000'}>{form.inputType==='net'?'목표 실수령액':'월 총 지급액'}</GuideLabel><div><MoneyInput label="급여액" value={form.amount} onChange={v=>update('amount',v)}/><b>원</b></div></label>
 <div className="field-grid"><label><GuideLabel title="공제대상 가족 수" meaning="소득세 계산에 반영되는 가족 수입니다. 직원 본인을 반드시 포함하며, 실제로 기본공제를 받을 수 있는 부양가족만 더합니다." example="직원 본인만 해당하면 1">공제대상 가족 수 (본인 포함)</GuideLabel><input type="number" min="1" max="11" value={form.dependents} onChange={e=>update('dependents',Math.max(1,Number(e.target.value)))}/></label><label><GuideLabel title="자녀 수" meaning="공제대상 가족 중 8세 이상 20세 이하인 자녀 수입니다. 해당 자녀가 없다면 0을 입력하세요." example="해당 자녀 2명 → 2">8세 이상 20세 이하 자녀</GuideLabel><input type="number" min="0" max="10" value={form.children} onChange={e=>update('children',Math.max(0,Number(e.target.value)))}/></label><label><GuideLabel title="기업 규모" meaning="고용보험의 사업주 부담 요율을 정하는 기준입니다. 일반적인 의원·소규모 병원은 보통 150인 미만을 선택합니다." example="직원 20명 의원 → 150인 미만">기업 규모</GuideLabel><select value={form.employerSize} onChange={e=>update('employerSize',e.target.value as CalculationInput['employerSize'])}><option value="under150">150인 미만 (0.25%)</option><option value="priority">우선지원대상 (0.45%)</option><option value="under1000">1,000인 미만 (0.65%)</option><option value="over1000">1,000인 이상 (0.85%)</option></select></label><label className="check"><input type="checkbox" checked={form.durunuri} onChange={e=>update('durunuri',e.target.checked)}/><span><GuideLabel title="두루누리 지원" meaning="근로자 10인 미만 사업장에서 월평균 보수 270만원 미만의 신규 가입 근로자라면 보험료 지원 가능성을 계산합니다." example="조건을 모두 충족할 때만 체크">두루누리 적용</GuideLabel><small>10인 미만·신규가입·보수 270만원 미만</small></span></label></div>
 <details><summary>연장·야간·휴일수당 설정 <span>선택</span></summary><div className="details-body"><label className="check compact"><input type="checkbox" checked={form.smallWorkplace} onChange={e=>update('smallWorkplace',e.target.checked)}/><span><GuideLabel title="5인 미만 사업장" meaning="상시근로자가 5명 미만이면 법정 가산수당 적용 방식이 달라질 수 있습니다. 사업장 전체 상시근로자 기준으로 판단하세요." example="상시근로자 4명 → 체크">5인 미만 사업장</GuideLabel></span></label><div className="triple"><label><GuideLabel title="연장근로 시간" meaning="월 소정근로시간을 초과해 일한 시간을 입력합니다. 급여대장이나 근태 기록의 월 합계를 사용하세요." example="이번 달 10시간 → 10">연장근로</GuideLabel><MoneyInput label="연장근로 시간" value={form.overtime} onChange={v=>update('overtime',v)}/></label><label><GuideLabel title="야간근로 시간" meaning="오후 10시부터 다음 날 오전 6시 사이에 근무한 월 합계 시간입니다." example="야간근무 합계 6시간 → 6">야간근로</GuideLabel><MoneyInput label="야간근로 시간" value={form.night} onChange={v=>update('night',v)}/></label><label><GuideLabel title="휴일근로 시간" meaning="주휴일이나 근로계약상 휴일에 실제로 근무한 월 합계 시간입니다." example="휴일근무 8시간 → 8">휴일근로</GuideLabel><MoneyInput label="휴일근로 시간" value={form.holiday} onChange={v=>update('holiday',v)}/></label></div></div></details>
 <details><summary>비과세 항목 설정 <span>선택</span></summary><div className="details-body triple"><label><GuideLabel title="비과세 식대" meaning="급여에 포함된 식대 중 비과세로 처리하는 금액입니다. 실제 급여명세서의 식대 항목을 입력하세요." example="월 식대 20만원 → 200,000">식대</GuideLabel><MoneyInput label="비과세 식대" value={form.meal} onChange={v=>update('meal',v)}/></label><label><GuideLabel title="비과세 보육수당" meaning="요건을 충족하는 근로자의 월 보육 관련 비과세 수당입니다. 급여명세서에 별도 항목이 있을 때만 입력하세요." example="월 20만원 지급 → 200,000">보육수당</GuideLabel><MoneyInput label="비과세 보육수당" value={form.childcare} onChange={v=>update('childcare',v)}/></label><label><GuideLabel title="자가운전보조금" meaning="직원 소유 차량을 업무에 사용하고 요건에 맞게 지급하는 비과세 보조금입니다. 단순 출퇴근 교통비는 넣지 않습니다." example="요건 충족 월 20만원 → 200,000">자가운전보조금</GuideLabel><MoneyInput label="비과세 자가운전보조금" value={form.transport} onChange={v=>update('transport',v)}/></label></div></details><button className="calculate" type="submit">총 인건비 계산하기 <span>→</span></button></form>
 <aside className="result-card" id="result"><div className="result-top"><div><span className="step light">02</span><h2>병원 예상 부담</h2></div><span className="live-dot">계산 완료</span></div><p className="result-caption">직원 1명당 월 총 인건비</p><strong className="total">{formatEasyWon(result.employerTotal)}</strong><span className="exact-money">정확히 {formatWon(result.employerTotal)}</span><div className="annual"><span>1년이면</span><b>{formatEasyWon(result.employerTotal*12)}</b></div><div className="money-compare"><div><span>직원이 받는 돈</span><strong>{formatEasyWon(result.net)}</strong></div><div><span>병원이 더 내는 돈</span><strong>+ {formatEasyWon(result.employerTotal-result.net)}</strong></div></div><div className="cost-bars" aria-label="월 인건비 구성"><div><span><b>세전 급여</b><i>{formatEasyWon(result.gross)}</i></span><progress max={result.employerTotal} value={result.gross}/></div><div><span><b>사업주 보험</b><i>{formatEasyWon(result.employerContributions.total)}</i></span><progress max={result.employerTotal} value={result.employerContributions.total}/></div><div><span><b>퇴직금 적립</b><i>{formatEasyWon(result.severance)}</i></span><progress max={result.employerTotal} value={result.severance}/></div></div>{result.overtimePay.total>0&&<div className="notice">가산수당 {formatWon(result.overtimePay.total)}이 총 지급액에 포함되었습니다.</div>}{result.durunuri.eligible&&<div className="support">두루누리 사업주 지원 예상 <b>- {formatWon(result.durunuri.employerSupport)}</b></div>}<details className="deduction-details"><summary>직원 공제 내역 자세히 보기 <span>{formatEasyWon(result.gross-result.net)}</span></summary><dl className="breakdown"><div><dt>국민연금</dt><dd>{formatWon(result.employeeContributions.pension)}</dd></div><div><dt>건강보험</dt><dd>{formatWon(result.employeeContributions.health)}</dd></div><div><dt>장기요양보험</dt><dd>{formatWon(result.employeeContributions.longTermCare)}</dd></div><div><dt>고용보험</dt><dd>{formatWon(result.employeeContributions.unemployment)}</dd></div><div><dt>소득세 + 지방소득세</dt><dd>{formatWon(result.tax.income+result.tax.local)}</dd></div></dl></details><p className="micro">큰 숫자는 만원 단위, 상세 금액은 원 단위입니다.</p></aside></section>
 <section className="guide" id="guide"><div><span className="eyebrow">CALCULATION STANDARD</span><h2>계산에 반영한 기준</h2></div><div className="guide-grid"><article><b>01</b><h3>2026 사회보험 요율</h3><p>국민연금 4.75%, 건강보험 3.595%, 장기요양 13.14%, 고용보험과 산재보험 사업주분을 반영합니다.</p></article><article><b>02</b><h3>국세청 간이세액 기준</h3><p>월 과세급여와 공제대상 가족 수, 8~20세 자녀 수를 반영해 원천징수 예상액을 계산합니다.</p></article><article><b>03</b><h3>숨은 비용까지 합산</h3><p>퇴직금 월 1/12 적립과 통상시급 209시간 기준 연장·야간·휴일수당을 함께 보여줍니다.</p></article></div></section>
 <SiteFooter/></main>}
