'use client';
import { FormEvent, useState } from 'react';
import { calculatePayroll, formatEasyWon, formatWon, type CalculationInput } from '../payroll';
import { SiteFooter, SiteHeader } from '../site-chrome';

const base:CalculationInput={inputType:'gross',amount:3500000,dependents:1,children:0,employerSize:'under150',durunuri:false,smallWorkplace:false,overtime:0,night:0,holiday:0,meal:0,childcare:0,transport:0};
const number=(s:string)=>Number(s.replace(/\D/g,''));
const months=Array.from({length:12},(_,i)=>i+1);

export default function PeriodPage(){
 const[startYear,setStartYear]=useState(2024),[startMonth,setStartMonth]=useState(1),[endYear,setEndYear]=useState(2026),[endMonth,setEndMonth]=useState(12),[form,setForm]=useState(base),[show,setShow]=useState(false);
 const startIndex=startYear*12+startMonth-1,endIndex=endYear*12+endMonth-1,duration=Math.max(1,endIndex-startIndex+1);
 const payroll=calculatePayroll(form);
 const segments=Array.from({length:endYear-startYear+1},(_,i)=>{const year=startYear+i;const from=year===startYear?startMonth:1;const to=year===endYear?endMonth:12;return{year,months:Math.max(0,to-from+1),from,to}}).filter(x=>x.months>0);
 const total=payroll.employerTotal*duration;
 const submit=(e:FormEvent)=>{e.preventDefault();setShow(true)};
 return <main><SiteHeader/><section className="sub-hero"><span className="eyebrow">PERIOD SIMULATION</span><h1>재직기간 총 인건비<br/>시뮬레이션</h1><p>채용부터 퇴사까지, 직원 한 명에게 필요한 전체 예산을 월 단위로 확인합니다.</p></section><section className="tool-page"><form className="tool-card" onSubmit={submit}><div className="section-head"><div><span className="step">01</span><h2>재직 조건</h2></div></div><div className="field-grid"><label><span>시작 시점</span><div className="year-month"><input aria-label="시작 연도" type="number" min="2020" max="2035" value={startYear} onChange={e=>setStartYear(Number(e.target.value))}/><select aria-label="시작 월" value={startMonth} onChange={e=>setStartMonth(Number(e.target.value))}>{months.map(m=><option key={m} value={m}>{m}월</option>)}</select></div></label><label><span>종료 시점</span><div className="year-month"><input aria-label="종료 연도" type="number" min={startYear} max="2040" value={endYear} onChange={e=>setEndYear(Math.max(startYear,Number(e.target.value)))}/><select aria-label="종료 월" value={endMonth} onChange={e=>setEndMonth(Number(e.target.value))}>{months.map(m=><option key={m} value={m}>{m}월</option>)}</select></div></label><label><span>입력 유형</span><select value={form.inputType} onChange={e=>setForm({...form,inputType:e.target.value as 'gross'|'net'})}><option value="gross">월 총 지급액 기준</option><option value="net">월 실수령액 기준</option></select></label><label><span>월 급여액</span><input value={form.amount.toLocaleString()} inputMode="numeric" onChange={e=>setForm({...form,amount:number(e.target.value)})}/></label><label><span>비과세 식대</span><input value={form.meal?form.meal.toLocaleString():''} inputMode="numeric" placeholder="0" onChange={e=>setForm({...form,meal:number(e.target.value)})}/></label><label><span>비과세 보육·교통 합계</span><input value={form.childcare+form.transport||''} inputMode="numeric" placeholder="0" onChange={e=>setForm({...form,childcare:Math.min(200000,number(e.target.value)),transport:Math.max(0,number(e.target.value)-200000)})}/></label></div><div className="period-preview"><span>선택한 재직기간</span><strong>{startYear}년 {startMonth}월 → {endYear}년 {endMonth}월</strong><b>총 {duration}개월</b></div><button className="calculate" type="submit">재직기간 시뮬레이션 <span>→</span></button></form>{show&&<section className="simulation-results"><div className="result-summary"><span>전체 재직기간 예상 부담</span><strong>{formatEasyWon(total)}</strong><small>정확히 {formatWon(total)} · {startYear}년 {startMonth}월–{endYear}년 {endMonth}월 · 총 {duration}개월</small></div><div className="year-list">{segments.map(s=><article key={s.year}><div><b>{s.year}년</b><span>{s.from}월–{s.to}월 · {s.months}개월</span></div><strong>{formatEasyWon(payroll.employerTotal*s.months)}</strong><div className="mini-numbers"><span>월 병원 부담 <b>{formatEasyWon(payroll.employerTotal)}</b></span><span>월 직원 실수령 <b>{formatEasyWon(payroll.net)}</b></span></div></article>)}</div></section>}</section><SiteFooter/></main>}
