import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { CSSProperties } from 'react';
import { SiteFooter, SiteHeader } from '../../site-chrome';

type Zone={n:string;title:string;input:string;example:string;box:[number,number,number,number]};
type Manual={kicker:string;title:string;description:string;calculator:string;image:string;zones:Zone[];analyze:string[];conclude:string[];help:string};
const manuals:Record<string,Manual>={
payroll:{kicker:'직원 인건비 계산기',title:'한 명의 실제 고용비용을 확인하는 법',calculator:'/',image:'/manual-screens/payroll-full.png',description:'빨간 번호 순서대로 근로계약서와 급여명세서의 숫자를 옮겨 적으세요.',zones:[
{n:'1',title:'계약 방식',input:'계약서가 세전 약정이면 총 지급액, 통장 입금액 약정이면 실수령액을 선택합니다. 실수령액에 퇴직금이 포함됐는지도 구분하세요.',example:'예: 네트 350만원, 퇴직금 별도 → 실수령액 기준·퇴직금 미포함',box:[7.2,32.3,47.2,9.1]},
{n:'2',title:'월 급여액',input:'상여금을 제외하고 매월 반복 지급하는 계약 금액을 원 단위로 입력합니다.',example:'예: 350만원 → 3,500,000',box:[7.2,45.3,47.2,4.7]},
{n:'3',title:'가족·기업 조건',input:'부양가족은 근로자 본인을 포함합니다. 해당 연령 자녀 수와 실제 사업장 규모를 선택합니다.',example:'예: 본인만 공제 → 가족 1, 자녀 0',box:[7.2,50.1,47.2,7.5]},
{n:'4',title:'수당·비과세',input:'연장·야간·휴일근로는 월 시간 합계, 비과세 항목은 급여명세서에 실제 적용할 월 금액을 넣습니다.',example:'예: 월 연장 10시간, 식대 200,000원',box:[7.2,58,47.2,5.5]}],analyze:['약정 월급 외 4대보험 사업주분과 퇴직금','직원 실수령액과 병원 실제 지출액의 차이','채용 제안 급여에 필요한 월·연간 예산'],conclude:['현재 급여 조건으로 채용 가능한지','세전·실수령 계약 중 어느 방식이 적합한지','수당·비과세를 포함한 급여 구조를 바꿀지'],help:'“월급 350만원”만 보고 채용하는 실수를 줄이고, 숨은 사용자 부담까지 포함한 실제 인건비로 채용 결정을 내릴 수 있습니다.'},
team:{kicker:'팀 인건비 계산기',title:'직원 전체의 월·연간 예산을 만드는 법',calculator:'/team',image:'/manual-screens/team-full.png',description:'직원 한 명을 한 줄로 보고, 같은 방식으로 전체 팀을 입력하세요.',zones:[
{n:'1',title:'직원별 한 줄 입력',input:'직무, 계약 기준, 월 급여, 가족 수, 자녀 수를 직원마다 입력합니다. 실제 이름 대신 직무명을 써도 됩니다.',example:'예: 간호조무사 / 총 지급액 / 2,800,000 / 1 / 0',box:[10,52.3,80,11.2]},
{n:'2',title:'직원 추가·삭제',input:'재직 중이거나 채용을 검토하는 인원만 남기고, 직원 추가 버튼으로 한 줄씩 늘립니다.',example:'현재 팀과 채용 후 팀은 따로 계산해 비교',box:[9.9,64.2,80.1,5.1]},
{n:'3',title:'팀 전체 계산',input:'같은 급여의 직원도 각각 한 줄로 입력한 뒤 계산합니다.',example:'결과에서 월 총액·연간 예산·1인 평균 확인',box:[9.9,72,80.1,5]}],analyze:['현재 팀의 월 총인건비와 12개월 예산','직원 1인 평균과 직무별 부담 차이','채용·급여 인상 전후의 총액 변화'],conclude:['현재 매출에서 적정 인력 규모인지','어떤 직무의 비용 비중이 높은지','다음 연도 인건비 예산을 얼마로 잡을지'],help:'여러 직원의 급여를 따로 합산하는 번거로움을 줄이고, 현재 조직과 채용 후 조직의 비용을 같은 기준으로 비교할 수 있습니다.'},
period:{kicker:'고용기간 계산',title:'특정 기간의 총 인건비를 추정하는 법',calculator:'/period',image:'/manual-screens/period-full.png',description:'입사월부터 예산을 확인하려는 종료월까지 순서대로 입력하세요.',zones:[
{n:'1',title:'시작·종료 시점',input:'급여가 실제 발생하는 첫 달과 마지막 달을 선택합니다. 시작월과 종료월 모두 계산됩니다.',example:'예: 2026년 3월 입사, 2027년 2월까지 예산',box:[17.1,47.7,65.8,6.3]},
{n:'2',title:'월 급여 조건',input:'세전·실수령 기준과 표준 월급, 매월 고정 비과세 수당을 입력합니다.',example:'예: 총 지급액 3,200,000원, 식대 200,000원',box:[17.1,54.3,65.8,11.2]},
{n:'3',title:'기간 확인·계산',input:'표시된 총 개월 수가 의도한 기간과 같은지 확인한 뒤 계산합니다.',example:'급여 인상이 있으면 전후 기간을 나누어 계산',box:[17.1,66.2,65.8,11.7]}],analyze:['계약기간 전체에 필요한 고용비용','연도별로 나뉘는 인건비 예산','급여 인상·계약 연장에 따른 누적 변화'],conclude:['계약직·대체인력의 총예산이 충분한지','올해와 다음 해에 각각 얼마를 배정할지','인력 유지기간을 늘릴 때 비용이 얼마나 느는지'],help:'월 인건비만 보다가 장기 누적비용을 놓치는 일을 막고, 계약기간과 회계연도에 맞춘 인력 예산을 만들 수 있습니다.'},
hiring:{kicker:'추가채용 수익성 계산',title:'새 직원의 손익분기점을 분석하는 법',calculator:'/hiring',image:'/manual-screens/hiring-full.png',description:'채용비용과 직원이 만드는 효과를 같은 월 기준으로 입력하세요.',zones:[
{n:'1',title:'채용할 직원',input:'직무와 계약 기준, 월 급여, 실제 비과세 식대를 입력합니다.',example:'예: 상담실장 / 실수령액 / 3,500,000원 / 식대 200,000원',box:[10,29.7,80,7.4]},
{n:'2',title:'초기·월 추가비용',input:'광고·교육·장비처럼 한 번 드는 비용과 매월 반복 운영비를 분리합니다.',example:'예: 광고 30만원, 교육 50만원, 월 운영비 20만원',box:[10,38.2,80,19]},
{n:'3',title:'직원이 만드는 효과',input:'직접 매출, 원장 시간 절감, 상담 전환 중 가까운 방식을 고르고 최근 실적의 객단가·건수·변동비를 넣습니다.',example:'예: 객단가 12만원, 하루 3건, 변동비 20%, 환불 3%',box:[10,60,80,22.7]}],analyze:['월 총 고용비와 필요한 손익분기 매출','몇 건부터 채용이 이익이 되는지','초기비 회수기간과 보수·기준·낙관 시나리오'],conclude:['지금 채용하는 것이 유리한지','급여 조건 또는 목표 매출을 조정할지','직원의 최소 월 성과를 얼마로 정할지'],help:'막연히 “바빠서 한 명 더”가 아니라, 채용비를 회수할 최소 생산성과 매출 목표를 숫자로 정할 수 있습니다.'},
startup:{kicker:'개원자금 계산기',title:'필요자금과 개원 후 버틸 기간을 설계하는 법',calculator:'/startup',image:'/manual-screens/startup-full.png',description:'견적서, 월 운영예산, 대출 조건을 준비해 네 구역을 차례로 입력하세요.',zones:[
{n:'1',title:'개원 전 일회성 비용',input:'보증금·인테리어·장비·가구·초도물품 등 실제 견적을 입력하고 예비비율을 정합니다.',example:'모든 견적의 부가세 포함·제외 기준을 통일',box:[7.4,16,85.2,18.3]},
{n:'2',title:'개원 후 월 운영비',input:'매월 나갈 임차료·인건비·리스·재료비와 매출 안정 전 버틸 개월 수를 입력합니다.',example:'예: 월 운영비 8천만원, 운전자금 6개월',box:[7.4,34.7,85.2,16.7]},
{n:'3',title:'자금 출처·금융비용',input:'자기자금과 대출별 조달액, 연 금리, 상환기간을 실제 조건대로 넣습니다.',example:'거치기간은 실제 상환표와 별도 비교',box:[7.4,52,85.2,19.6]},
{n:'4',title:'손익분기 조건',input:'매출총이익률, 환자 1명 평균매출, 월 진료일을 보수적 사업계획 기준으로 입력합니다.',example:'예: 이익률 70%, 객단가 10만원, 월 24일',box:[7.4,72.5,85.2,14.3]}],analyze:['개원 총현금과 조달 후 부족·여유자금','대출 원리금을 포함한 월 현금유출','손익분기 매출과 월·일 최소 환자 수'],conclude:['현재 자금구조로 개원이 가능한지','운전자금을 몇 개월 확보해야 안전한지','장비·인테리어 또는 개원 규모를 줄일지'],help:'공사비만 계산하고 운영자금이 바닥나는 위험을 줄이며, 매출 안정 시점까지 필요한 생존자금을 함께 준비할 수 있습니다.'}}

export function generateStaticParams(){return Object.keys(manuals).map(slug=>({slug}))}
export default async function ManualPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const m=manuals[slug];if(!m)notFound();return <main><SiteHeader/><article className="manual-page visual-manual"><div className="manual-topbar"><Link className="manual-back" href={m.calculator}>← 계산기로 돌아가기</Link><a className="manual-download" href="/thefount-calculator-manual-summary.pdf" download>화면형 전체 매뉴얼 PDF ↓</a></div><header className="manual-heading"><span>{m.kicker} · VISUAL GUIDE</span><h1>{m.title}</h1><p>{m.description}</p></header><div className="visual-guide-grid"><figure className="manual-screen"><img src={m.image} alt={`${m.kicker} 실제 입력 화면`}/>{m.zones.map(z=><span key={z.n} className="screen-zone" style={{'--l':`${z.box[0]}%`,'--t':`${z.box[1]}%`,'--w':`${z.box[2]}%`,'--h':`${z.box[3]}%`} as CSSProperties}><b>{z.n}</b></span>)}</figure><div className="visual-callouts">{m.zones.map(z=><section key={z.n}><span>{z.n}</span><div><h2>{z.title}</h2><p>{z.input}</p><small>{z.example}</small></div></section>)}</div></div><section className="decision-intro"><span>CALCULATOR VALUE</span><h2>이 계산으로 병원은 무엇을 판단할 수 있나요?</h2><p>계산값 자체보다 중요한 것은 숫자를 비교해 운영 결정을 내리는 것입니다.</p></section><div className="decision-grid"><section><span>01 · 분석</span><h3>숫자로 확인할 수 있는 것</h3><ul>{m.analyze.map(x=><li key={x}>{x}</li>)}</ul></section><section><span>02 · 결론</span><h3>병원이 내릴 수 있는 결정</h3><ul>{m.conclude.map(x=><li key={x}>{x}</li>)}</ul></section><section className="decision-help"><span>03 · 도움</span><h3>실무적으로 이런 도움이 됩니다</h3><p>{m.help}</p></section></div><aside className="manual-note"><strong>입력 전 한 번 더 확인하세요.</strong><p>같은 기간과 같은 기준의 숫자를 입력해야 비교가 정확합니다. 결과는 의사결정용 예상치이며 실행 전 전문가와 확인하세요.</p></aside><Link className="manual-final-cta" href={m.calculator}>화면을 보며 계산해보기 <span>→</span></Link></article><SiteFooter/></main>}
