'use client';
import {FormEvent,useMemo,useState} from 'react';
import {SiteFooter,SiteHeader} from '../site-chrome';
import {calculateStartup,startupEasyWon,startupWon,type FundingSource,type StartupInput} from './startup';

const initialLabels=['임대보증금','권리금·중개수수료','인테리어·간판','의료장비 구매·보증금','가구·집기·전산','초도 의약품·소모품','인허가·세무·법률','홈페이지·브랜딩','개원 마케팅','채용·교육비'];
const monthlyLabels=['임대료·관리비','직원 총인건비','장비 리스료','재료·소모품비','광고·마케팅비','전산·세무·노무비','공과금·폐기물·보안','원장 생활비'];
const fundingMeta=[['bank','은행 대출'],['guarantee','신용보증기금 연계대출'],['personal','개인 자금'],['other','타인 자금']] as const;
const initial:StartupInput={oneTimeCosts:[50000000,0,150000000,120000000,20000000,10000000,5000000,10000000,20000000,5000000],monthlyCosts:[8000000,18000000,5000000,6000000,5000000,1000000,2000000,5000000],reserveMonths:6,contingencyRate:10,funding:[{kind:'bank',amount:200000000,annualRate:5.2,termYears:7},{kind:'guarantee',amount:100000000,annualRate:4.2,termYears:5},{kind:'personal',amount:200000000,annualRate:0,termYears:0},{kind:'other',amount:0,annualRate:6,termYears:3}],grossMarginRate:70,averageRevenue:100000,workDays:24};
const number=(value:string)=>Number(value.replace(/[^0-9.]/g,''))||0;
const Money=({value,onChange,label}:{value:number;onChange:(value:number)=>void;label:string})=><div className="startup-money"><input aria-label={label} inputMode="numeric" value={value?value.toLocaleString('ko-KR'):''} onChange={e=>onChange(number(e.target.value))} placeholder="0"/><span>원</span></div>;

export default function StartupPage(){
 const[form,setForm]=useState(initial),[submitted,setSubmitted]=useState(initial),[show,setShow]=useState(false);
 const result=useMemo(()=>calculateStartup(submitted),[submitted]);
 const cost=(group:'oneTimeCosts'|'monthlyCosts',index:number,value:number)=>setForm(current=>({...current,[group]:current[group].map((item,i)=>i===index?value:item)}));
 const fund=(index:number,patch:Partial<FundingSource>)=>setForm(current=>({...current,funding:current.funding.map((item,i)=>i===index?{...item,...patch}:item)}));
 const submit=(event:FormEvent)=>{event.preventDefault();setSubmitted(form);setShow(true);setTimeout(()=>document.getElementById('startup-result')?.scrollIntoView({behavior:'smooth',block:'start'}),20)};
 return <main><SiteHeader/><section className="sub-hero startup-hero"><span className="eyebrow">CLINIC OPENING CAPITAL</span><h1>개원 비용보다 중요한 건,<br/>버틸 수 있는 자금입니다.</h1><p>초기 투자비와 개원 후 운영비, 자금 출처별 이자와 상환액까지 반영해 필요한 개원자금을 계산합니다.</p></section>
 <section className="tool-page wide startup-page"><form className="tool-card startup-form" onSubmit={submit}>
 <header className="startup-section-head"><span className="step">01</span><div><h2>개원 전 일회성 비용</h2><p>견적을 아직 받지 않았다면 예상금액으로 시작하세요.</p></div></header><div className="startup-cost-grid">{initialLabels.map((label,index)=><label key={label}><span>{label}</span><Money label={label} value={form.oneTimeCosts[index]} onChange={value=>cost('oneTimeCosts',index,value)}/></label>)}</div><div className="startup-inline"><label><span>예비비</span><div><input type="number" min="0" max="50" value={form.contingencyRate} onChange={e=>setForm({...form,contingencyRate:number(e.target.value)})}/><b>%</b></div></label><p>공사 변경·개원 지연 등 예상 밖 지출에 대비합니다.</p></div>
 <header className="startup-section-head"><span className="step">02</span><div><h2>개원 후 월 운영비</h2><p>대출 상환액은 아래 자금계획에서 자동으로 추가됩니다.</p></div></header><div className="startup-cost-grid">{monthlyLabels.map((label,index)=><label key={label}><span>{label}</span><Money label={label} value={form.monthlyCosts[index]} onChange={value=>cost('monthlyCosts',index,value)}/></label>)}</div><div className="startup-inline"><label><span>운전자금 확보기간</span><div><input type="number" min="0" max="24" value={form.reserveMonths} onChange={e=>setForm({...form,reserveMonths:number(e.target.value)})}/><b>개월</b></div></label><p>매출이 안정되기 전까지 버틸 운영비를 포함합니다.</p></div>
 <header className="startup-section-head"><span className="step">03</span><div><h2>자금 출처와 금융비용</h2><p>개인자금은 금리와 기간을 0으로 두면 상환액이 발생하지 않습니다.</p></div></header><div className="funding-table"><div className="funding-row funding-head"><span>자금 출처</span><span>조달 금액</span><span>연 금리</span><span>상환기간</span></div>{form.funding.map((source,index)=><div className="funding-row" key={source.kind}><b>{fundingMeta[index][1]}</b><Money label={`${fundingMeta[index][1]} 조달 금액`} value={source.amount} onChange={value=>fund(index,{amount:value})}/><label><input aria-label={`${fundingMeta[index][1]} 연 금리`} type="number" min="0" max="30" step="0.1" value={source.annualRate} onChange={e=>fund(index,{annualRate:number(e.target.value)})}/><span>%</span></label><label><input aria-label={`${fundingMeta[index][1]} 상환기간`} type="number" min="0" max="30" value={source.termYears} onChange={e=>fund(index,{termYears:number(e.target.value)})}/><span>년</span></label></div>)}</div><p className="finance-note">대출은 원리금균등상환을 가정합니다. 보증료, 중도상환수수료, 거치기간은 실제 금융기관 조건에 따라 별도로 확인하세요.</p>
 <header className="startup-section-head"><span className="step">04</span><div><h2>손익분기 계산 조건</h2><p>개원 후 월 현금유출을 감당하는 데 필요한 매출과 환자 수를 계산합니다.</p></div></header><div className="startup-three"><label><span>매출총이익률</span><div><input type="number" min="1" max="100" value={form.grossMarginRate} onChange={e=>setForm({...form,grossMarginRate:number(e.target.value)})}/><b>%</b></div></label><label><span>환자 1명 평균 매출</span><Money label="환자 1명 평균 매출" value={form.averageRevenue} onChange={value=>setForm({...form,averageRevenue:value})}/></label><label><span>월 진료일</span><div><input type="number" min="1" max="31" value={form.workDays} onChange={e=>setForm({...form,workDays:number(e.target.value)})}/><b>일</b></div></label></div><button className="calculate" type="submit">필요 개원자금 계산하기 <span>→</span></button></form>
 {show&&<section className="startup-results" id="startup-result"><div className={`startup-verdict ${result.fundingGap>=0?'safe':'short'}`}><span>{result.fundingGap>=0?'현재 자금계획으로 개원 가능':'자금계획 보완 필요'}</span><strong>필요 개원자금 {startupEasyWon(result.requiredCapital)}</strong><p>{result.fundingGap>=0?`필요자금보다 ${startupWon(result.fundingGap)}의 여유가 있습니다.`:`현재 조달계획에서 ${startupWon(Math.abs(result.fundingGap))}이 부족합니다.`}</p></div><div className="startup-kpis"><article><span>일회성 개원비</span><b>{startupEasyWon(result.oneTimeTotal)}</b><small>예비비 {startupWon(result.contingency)} 포함</small></article><article><span>{submitted.reserveMonths}개월 운전자금</span><b>{startupEasyWon(result.reserve)}</b><small>대출 상환 전 운영비 기준</small></article><article><span>월 대출 상환액</span><b>{startupEasyWon(result.monthlyDebtPayment)}</b><small>첫 달 이자 약 {startupWon(result.firstMonthInterest)}</small></article><article><span>총 예상 이자</span><b>{startupEasyWon(result.totalInterest)}</b><small>입력한 전체 상환기간 기준</small></article></div><div className="startup-result-grid"><article><h3>월 현금유출</h3><dl><div><dt>기본 운영비</dt><dd>{startupWon(result.monthlyOperating)}</dd></div><div><dt>대출 원리금</dt><dd>{startupWon(result.monthlyDebtPayment)}</dd></div><div className="sum"><dt>월 합계</dt><dd>{startupWon(result.monthlyCashOut)}</dd></div></dl></article><article><h3>최소 운영 목표</h3><dl><div><dt>손익분기 월매출</dt><dd>{startupWon(result.breakEvenRevenue)}</dd></div><div><dt>월 필요 환자 수</dt><dd>{result.monthlyPatients.toLocaleString()}명</dd></div><div className="sum"><dt>하루 필요 환자 수</dt><dd>{result.dailyPatients.toLocaleString()}명</dd></div></dl></article></div><div className="funding-breakdown"><h3>자금 출처별 상환계획</h3>{result.debt.map((source,index)=><div key={source.kind}><span>{fundingMeta[index][1]}</span><b>{startupWon(source.amount)}</b><span>월 상환 {startupWon(source.monthlyPayment)}</span><span>총 이자 {startupWon(source.totalInterest)}</span></div>)}</div><p className="legal-note">본 결과는 입력값과 원리금균등상환 가정에 따른 참고용 추정치입니다. 실제 대출금리·보증료·세금·상환조건은 금융기관 및 전문가에게 확인하세요.</p></section>}</section><SiteFooter/></main>}

